### ISSUE TITLE
Normalise function and lazy vs eager normalization

### ISSUE THREAD

**Issue by jrstrunk** [gleam-lang/time#2]
What are your plans for the `normalise` function in #1? By including it in the public interface, it seems there is an intention for lazily computed normalization after adds and subtracts. Is this correct? I understand the use case for this, but personally think we should consider eager normalization for a couple of reasons. I want to make sure of the intention before I type things out though.

**Comment by jrstrunk** [comment]
I see the `normalise` function has been made private, this is less of a worry now!

**Comment by lpil** [comment]
Yes, following initial discussion on discord

**Comment by jrstrunk** [comment]
I see I should probably join the discord haha

**Comment by lpil** [comment]
It's a lovely place!
