### ISSUE TITLE
Timestamp monotonicity

### ISSUE THREAD

**Issue by jrstrunk** [gleam-lang/time#3]
I know you are aware of this because of our previous conversations, but the `timestamp.now` function in #1 comes with a pretty big foot gun since it does not record monotonic time. I have a tempo v6 release ready all except including this timestamp type we are working on, and in it I decided to remove all the `time_type.now` functions. There are just too many issues users can find themselves accidentally walking into with them. Instead, I have a single `tempo.now` function that returns a new value of type `instant`, which can then be converted into any other time type if needed. We can work through all the points if you'd like, but I would vote to hold off on including it at least for now.

**Comment by lpil** [comment]
Hello! I agree, we need to think carefully about monotonicity.

Could you detail the specific issues you mention please. We can't reason about them without details!

**Comment by jrstrunk** [comment]
Sure! In tempo I initially added monotonic time to every time value to avoid timing bugs as we had discussed previously. The issue I found with that is it broke the `==` operator in non-obvious ways to the user when serializing and then deserializing datetime / time values. For example:
```gleam
let now = datetime.now()

now == now // True
now == { now |> to_database_and_back |> datetime.from_dynamic } // Not true
```

I was alerted to this because in one of my programs I created a type with a `created_at` field of the `datetime.now()` value when it was constructed. When my program constructed it and held that initial instance in memory, that instance would not be equal to the instance that was sent to the db and then later retrieved. I noticed this because all my database round-trip tests were failing. That prompted me to stop including monotonic time in all types in tempo (unreleased v6) because I did not want to make assumptions about how users would use the types.

I think it is fine to include monotonic time in general time types in other languages, but things have to be a little different here since Gleam doesn't have operator overloading.

To solve for users incorrectly using `datetime.now` to time things in tempo, I made timing things the correct way the most convenient way to do it! Then also made timing things the incorrect way inconvenient. My reasoning is that if users can do:
```gleam
import tempo

let timer = tempo.now()

// Do task

let elapsed = tempo.since(timer)
```
when why would they do something incorrect like:
```gleam
import tempo
import tempo/datetime

let start_datetime = tempo.now() |> instant.to_datetime

// Do task

let elapsed = datetime.difference(from: start_datetime)
```
instead?

**Comment by lpil** [comment]
Sorry, I don't understand how that's related to your original comment of `timestamp.now` being error prone due to not being monotonic. I'm misunderstanding as to me it reads that you prefer the design this library presently has?

**Comment by jrstrunk** [comment]
Currently, I think adding a `gleam/instant` module and then providing `instant.now()` and `instant.to_timestamp` functions is the least error-prone. But there is a lot to work through there. I think the gleam_time module should release without a way to get the current timestamp first, then later we can add it after sufficient discussion.

**Comment by lpil** [comment]
I very strongly disagree- there must be a way to get the current timestamp. This is going to be one of the most commonly used functions, and monotonic time is uncommonly used compared to wall clock time. Monotonic time is largely only useful for ordering, and to a much lesser extent recording small elapsed durations (but it's not much better at that than wall time and has almost all the same pitfalls).

Is the concern that people will not understand that `timestamp.now()` is not monotonic?

**Comment by giacomocavalieri** [comment]
> Is the concern that people will not understand that timestamp.now() is not monotonic?

To be fair I think the documentation that's here is already doing a great job at that. Maybe we could add that notice again in the compare function to make it harder for folks to miss that

**Comment by lpil** [comment]
Would a name like `current_system_time` be better than `now`? Perhaps it would hint that the time can change.

I'm not sure what you'd call a monotonic version in that case. `current_system_monotonic_time`? 😁

**Comment by jrstrunk** [comment]
> Is the concern that people will not understand that timestamp.now() is not monotonic?

Yes exactly!

I don't think there is enough documentation in the world that will suffice! No matter how many warnings you put up in the documentation, users will still see a `timestamp.now` LSP autocomplete or AI suggestion and just blindly use it without ever even seeing the documentation. Everyone knows what time is, and that will make people think they don't need to read documentation on it.

Providing a `timestamp.now` function is convenience over correctness and I do not think that fits with the Gleam ethos! (Respectfully, I know you are the creator and I am just a mere user 😅)

The `timestamp.now` function is not very useful on its own; it is almost always going to be used right before another function. If we create a rich enough ecosystem, I do not think users will need a `timestamp.now` function nearly as much. Adding the `now` function at this point is risking having to make breaking changes later. I think dedicating the current system time to its own module is more correct and can be just as ergonomic.

Tempo v6 is based on these things, and there are many changes from v5. I can host the unreleased documentation somewhere if you want to look over its principles in completeness for context. (Or I could release tempo v6 now if we wanted to release this package as v0.1 and only include the types with getters / setters!)

**Comment by jrstrunk** [comment]
For a concrete reference, I typed up gtempo v6's docs and hosted them here: https://gtempo.jrstrunk.com/index.html (served via Wisp 😎). Also if you are using gtempo anywhere, you could clone the repo, check out the v6 branch, and add it as a path dep to see how it feels! The biggest change is that there is only one `now` function now and a lot more `tempo` module functions that deal with the current system time. These could have also all been put into the `instant` module and taken an `instant` value as the first arg.

It is fine if you do not think my perspective is correct and want to add `timestamp.now` to the standard package, that might just be the diverging design pattern between gtempo and the standard lib if so :)

**Comment by lpil** [comment]
Now has been removed, there is now only a function to get the system time. Thanks both
